"""initial 3

Revision ID: ccb84bd3aad3
Revises: b75dc0e63ca0
Create Date: 2022-04-16 22:45:49.313691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb84bd3aad3'
down_revision = 'b75dc0e63ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
